#!/bin/bash

clear

echo "cual es la IP de tu ordenador?"

read ipServidor

echo  "Elige el nombre del servidor"

read nombreServidor

echo Elige el puerto del servidor: 

read puertoServidor

echo Iniciando tu servidor... 

podman run -d --name=$nombreServidor -p $puertoServidor:30000/udp -e CLI_ARGS="--gameid devtest" luanti:latest

clear

echo "Tu servidor ya esta funcionando con la IP 127.0.0.1 o bien con $ipServidor y con el puerto $puertoServidor"
