#!/bin/bash

echo  Elige el nombre del servidor

read nombreServidor

echo Elige el puerto del servidor

read puertoServidor

podman run --name=$nombreServidor -p $puertoServidor -e CLI_ARGS="--gameid devtest" minetest:latest
