#!/bin/bash
echo  Elige el nombre del servidor

read nombreServidor

podman run --name=$nombreServidor -e CLI_ARGS="--gameid devtest" minetest:latest

echo Elige el puerto del servidor 

read elegirPuerto
